const KEYS = [
  [
    { base: "`", shift: "~", finger: "ll" },
    { base: "1", shift: "!", finger: "ll" },
    { base: "2", shift: "@", finger: "lr" },
    { base: "3", shift: "#", finger: "lm" },
    { base: "4", shift: "$", finger: "lf" },
    { base: "5", shift: "%", finger: "lf" },
    { base: "6", shift: "^", finger: "rf" },
    { base: "7", shift: "&", finger: "rf" },
    { base: "8", shift: "*", finger: "rm" },
    { base: "9", shift: "(", finger: "rr" },
    { base: "0", shift: ")", finger: "rl" },
    { base: "-", shift: "_", finger: "rl" },
    { base: "=", shift: "+", finger: "rl" },
    {
      base: "Backspace ⌫",
      shift: "Backspace &larr;",
      finger: "rl",
      type: "special",
    },
  ],
  [
    { base: "Tab ↹", shift: "Tab ↹", finger: "ll", type: "special" },
    { base: "q", shift: "Q", finger: "ll" },
    { base: "w", shift: "W", finger: "lr" },
    { base: "e", shift: "E", finger: "lm" },
    { base: "r", shift: "R", finger: "lf" },
    { base: "t", shift: "T", finger: "lf" },
    { base: "y", shift: "Y", finger: "rf" },
    { base: "u", shift: "U", finger: "rf" },
    { base: "i", shift: "I", finger: "rm" },
    { base: "o", shift: "O", finger: "rr" },
    { base: "p", shift: "P", finger: "rl" },
    { base: "[", shift: "{", finger: "rl" },
    { base: "]", shift: "}", finger: "rl" },
    { base: "\\", shift: "|", finger: "rl", type: "special" },
  ],
  [
    { base: "Caps Lock ⇪", shift: "Enter", finger: "rl", type: "special" },
    { base: "a", shift: "A", finger: "ll" },
    { base: "s", shift: "S", finger: "lr" },
    { base: "d", shift: "D", finger: "lm" },
    { base: "f", shift: "F", finger: "lf" },
    { base: "g", shift: "G", finger: "lf" },
    { base: "h", shift: "H", finger: "rf" },
    { base: "j", shift: "J", finger: "rf" },
    { base: "k", shift: "K", finger: "rm" },
    { base: "l", shift: "L", finger: "rr" },
    { base: ";", shift: ":", finger: "rl" },
    { base: "'", shift: '"', finger: "rl" },
    { base: "Enter", shift: "Enter", finger: "rl", type: "special" },
  ],
  [
    { base: "Shift ⇧", code: "ShiftLeft", finger: "ll", type: "special" },
    { base: "z", shift: "Z", finger: "ll" },
    { base: "x", shift: "X", finger: "lr" },
    { base: "c", shift: "C", finger: "lm" },
    { base: "v", shift: "V", finger: "lf" },
    { base: "b", shift: "B", finger: "lf" },
    { base: "n", shift: "N", finger: "rf" },
    { base: "m", shift: "M", finger: "rf" },
    { base: ",", shift: "<", finger: "rm" },
    { base: ".", shift: ">", finger: "rr" },
    { base: "/", shift: "?", finger: "rl" },
    { base: "Shift ⇧", code: "ShiftRight", finger: "rl", type: "special" },
  ],
  [
    { base: "Ctrl", shift: "Ctrl", type: "special" },
    { base: "Win", shift: "Win", type: "special" },
    { base: "Alt", shift: "Alt", type: "special" },
    { base: " ", shift: "", type: "spacebar", finger: "rt" },
    { base: "Alt", shift: "Alt", type: "special" },
    { base: "Ctrl", shift: "Ctrl", type: "special" },
    // { base: "☰", shift: "☰", type: "special" },
    // { base: "Arrow", shift: "Arrow", type: "special" },
  ],
];

const ShiftRight = new Set([
  "Q",
  "W",
  "E",
  "R",
  "T",
  "A",
  "S",
  "D",
  "F",
  "G",
  "Z",
  "X",
  "C",
  "V",
  "B",
  "!",
  "@",
  "$",
  "%",
]);
const ShiftLeft = new Set([
  "Y",
  "U",
  "I",
  "O",
  "P",
  "{",
  "}",
  "|",
  "H",
  "J",
  "K",
  "L",
  ":",
  '"',
  "N",
  "M",
  "<",
  ">",
  "?",
]);
export default KEYS;
export { ShiftLeft, ShiftRight };
